### ISSUE TITLE
Descriptor indexing on images.

### ISSUE THREAD

**Issue by DoeringChristian** [attackgoat/screen-13#14]
When having an unbounded array of images in a Shader, the program exits with the assert_ne at graph/resolver.rs:512.
Because spirq-rs returns 0 as descriptor count for an unbounded descriptor array.

Shader code: 
```glsl
layout(set = 1, binding = 0, rgba8) writeonly uniform image2D dst[];
```

**Comment by attackgoat** [comment]
I tried reproducing this issue and got a different failure case; no images bound but also no errors. Here are my tests:
[attackgoat/bindless](https://github.com/attackgoat/screen-13/blob/38b22a5d51b6001f849aa774ab9b69664c94d6dc/examples/fuzzer.rs#L141)

This should definitely be a supported case, and I think I see the solution and can work on this unless you would like to take it.

**Comment by DoeringChristian** [comment]
I would love to try to figure it out but I'm not sure that I can. I don't have that much experience with Rust and Vulkan.

**Comment by DoeringChristian** [comment]
I had the same issue with the image not appearing but with a single bound image. This is on a different pc with Intel internal graphics on Linux so I thought it was a driver issue.

**Comment by DoeringChristian** [comment]
I'm a little confused because I get a whole lot of validation layer errors because the descriptor indexing features are not enabled. Is there a reason why or should they be enabled?

**Comment by attackgoat** [comment]
> Is there a reason why or should they be enabled?

I pushed a commit just now to address this, although it is not the complete fix for the feature yet

**Comment by DoeringChristian** [comment]
There was a bug with the bindless flags in #15
When having the following shader code:
```glsl
layout(set = 0, binding = 0) writeonly uniform image dst[];
layout(set = 1, binding = 0) buffer ...
layout(set = 1, binding = 1) buffer...
```
I think I have fixed it but I don't know if it is any good.
[fork](https://github.com/DoeringChristian/screen-13)

**Comment by attackgoat** [comment]
The fix looks fantastic to me and address the pointer-sharing-between-calls bug that my test cases didn't uncover.

**Comment by DoeringChristian** [comment]
Sorry for the grammar in the title btw. 
Everything seems to be working with debug disabled now. Thanks for your quick response and fix. 
I do however have an error popping up in debug mode:
```
vkCmdBeginRenderPass: Image view #0 created from an image with usage set as 0x9F, but image info #0 used to create the framebuffer had usage set as 0x1F The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)
```
I think I have fixed it in my [fork](https://github.com/DoeringChristian/screen-13).
p.s. Should maybe have opened another Issue for that.

**Comment by attackgoat** [comment]
Thanks for letting me know and the patch!

The fix you applied will work, but I would like to instead use the flags that are stored a few lines above your fix, I think that will do the same thing and still provide the correct info on other hardware, if they don't support `INPUT_ATTACHMENT` surfaces. I'll put that onto `master` directly and do a release with this.
