### ISSUE TITLE
Adding helper functions for uploading to buffers etc.

### ISSUE THREAD

**Issue by DoeringChristian** [attackgoat/screen-13#28]
Since uploading to a Buffer on creation is done very frequently I wonder weather a constructor that takes a slice is a good idea?
This would require bytemuck as a dependency though.

**Comment by attackgoat** [comment]
I think this can be done without `bytemuck` - and it sounds like a good idea. An optional `bytemuck` dependency where we do the mucking for you would also be helpful too.
