### ISSUE TITLE
Panic on minimize event with error `STATUS_ACCESS_VIOLATION` or `STACK_BUFFER_OVERRUN` depending on example

### ISSUE THREAD

**Issue by HeavyRain266** [attackgoat/screen-13#35]
Hello, I'm getting weird panics when window is getting minimized on Windows.

hello_world.rs panics with: `STATUS_ACCESS_VIOLATION`and every other example except raytracing (not tested) panics with: `STACK_BUFFER_OVERRUN`.

I found it really hard to debug, second error code is definitely weird because it doesn't leak memory or anything, general usage even becomes 2x smaller for few seconds before panic 😕.

**Comment by seabassjh** [comment]
I don't have an explanation or answer to that problem, but I too experience this, and I've seen this same error occur on every ash-based render app in Rust I've tried.  [kajiya](https://github.com/EmbarkStudios/kajiya) is one of them.  Perhaps there's some edge case that needs handled with winit and the Windows API side of things that nobody has took the time and effort to do?

**Comment by attackgoat** [comment]
I spammed the `swapchain.rs` with a bunch of `trace!()` logs and narrowed this down to incorrect usage of the destroy function.

Thanks for the bug @HeavyRain266 and the helpful analysis @seabassjh! I don't use Windows often and missed this.

There may be more clean-up needed; and thought put into #36 before it merges but I may not have the time to do that over the next week or so. I will attempt to merge this as soon as I can.

**Comment by HeavyRain266** [comment]
Thanks for investigating this, I'm also not using windows often too, Wayland extension used by winit  to share window surface with the Compositor doesn't  specify such event a minimize so I couldn't encounter that crash anytime soon but potential users of my game or engine could on either windows or macOS through moltenvk.

Here is said extension spec generated from XML: https://wayland.app/protocols/xdg-shell
