### ISSUE TITLE
Ray Trace Examples Error on "Device Lost" in Release Builds

### ISSUE THREAD

**Issue by cryscan** [attackgoat/screen-13#46]
System: Windows Server 2022 Datacenter 21H2
GPU: Quadro RTX 4000
Branch: main @ a636993

Ray tracing examples work in debug builds, but running `cargo run --release --example rt_triangle` the app freezes and there is an "device lost" error.

**Comment by attackgoat** [comment]
Interesting - I get the same result on Ubuntu with an RTX 3090, driver version: 525.60.11. I've only run ray tracing in debug mode but I should have the time over the next two weeks to look into this.

**Comment by attackgoat** [comment]
@cryscan Thanks for reporting this issue!

I'm pushing the fix out as v0.7.1. If you see anything else please feel free to re-open this issue or create a new one.
